// src/cli/plan.js
// `aiep plan "<idea>" [--id WO-XXXX] [--level L1..L4] [--no-ai] [--force] [--json]`
//
// Proof of concept for RFC-0002: turn an idea into a DRAFT Work Order for human
// review. It uses a local model (Ollama) to propose title/objective/deliverables
// and a suggested ReviewLevel, falling back to a template when the model is
// unavailable. It writes ONLY a planning document (status: backlog) — it never
// generates source code, builds, or deploys. Fully within the v1.0 Scope Lock.

import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadConfig } from '../core/config.js';
import { VALID_LEVELS } from '../core/workorders.js';
import { probeOllama, ollamaGenerate } from '../reviewers/ollama.js';
import { c, log } from '../core/logger.js';

/** Next WO id = max existing numeric id + 1, zero-padded to 4 digits. */
export function nextWorkOrderId(workOrdersDir) {
  let max = 0;
  if (existsSync(workOrdersDir)) {
    for (const name of readdirSync(workOrdersDir)) {
      const m = name.match(/^WO-(\d{1,})$/);
      if (m) max = Math.max(max, Number.parseInt(m[1], 10));
    }
  }
  return `WO-${String(max + 1).padStart(4, '0')}`;
}

/**
 * Parse the model's labelled response into structured Work Order fields.
 * Lenient: any missing field is left undefined for the caller to default.
 * @param {string} text
 */
export function parsePlanResponse(text) {
  const out = {};
  const grab = (label) => {
    const m = text.match(new RegExp(`^${label}:\\s*(.+)$`, 'im'));
    return m ? m[1].trim() : undefined;
  };
  out.title = grab('TITLE');
  const lvl = grab('LEVEL');
  if (lvl) {
    const norm = lvl.toUpperCase().match(/L[1-4]/);
    if (norm) out.level = norm[0];
  }
  out.rationale = grab('RATIONALE');
  out.objective = grab('OBJECTIVE');
  // Deliverables: lines after a DELIVERABLES: label, as "- item".
  const dm = text.match(/DELIVERABLES:\s*\n([\s\S]*?)(?:\n\s*\n|\n[A-Z_]+:|\s*$)/i);
  if (dm) {
    out.deliverables = dm[1]
      .split(/\r?\n/)
      .map((l) => l.replace(/^\s*[-*]\s*/, '').trim())
      .filter(Boolean);
  }
  return out;
}

/** Render a valid draft Work Order markdown. */
export function renderWorkOrder({ id, title, level, rationale, objective, deliverables, idea, usedAi }) {
  const dels = (deliverables && deliverables.length ? deliverables : ['(define deliverables)'])
    .map((d) => `  - ${d}`)
    .join('\n');
  return `---
id: ${id}
title: "${(title || idea).replace(/"/g, "'").slice(0, 120)}"
phase: Idea
reviewLevel: ${level}
status: backlog
owner: unassigned
---

# ${id} — ${title || idea}

> **DRAFT** generated by \`aiep plan\`${usedAi ? ' (AI-assisted)' : ' (template — model unavailable)'}.
> Review and refine before implementation. This document does not authorize code changes.

## Idea

${idea}

## Objective

${objective || idea}

## Deliverables

${dels}

## Definition of Done

- [ ] Deliverables implemented.
- [ ] Reviewers for ReviewLevel ${level} executed (or documented disposition).
- [ ] No unresolved CRITICAL/HIGH findings.
- [ ] \`aiep validate\` passes.

## ReviewLevel — ${level}

${rationale || 'Suggested by aiep plan; confirm against the Review Level Policy before implementation.'}

## Traceability

- Origin: \`aiep plan\` (RFC-0002 PoC)
- Governance: docs/governance/REVIEW-LEVEL-POLICY.md
`;
}

function buildPlanPrompt(idea) {
  return [
    'You are a senior engineering planner. Turn the IDEA into a concise Work Order draft.',
    'Respond ONLY in this exact labelled format (no extra prose):',
    'TITLE: <short imperative title>',
    'LEVEL: <one of L1, L2, L3, L4>',
    'RATIONALE: <one sentence why that review level>',
    'OBJECTIVE: <2-3 sentences>',
    'DELIVERABLES:',
    '- <deliverable>',
    '- <deliverable>',
    '',
    'Review level guidance: L1 docs/low-risk; L2 normal code; L3 architecture/integration; L4 only genuinely high-risk (auth, payment, security, critical migration).',
    '',
    `IDEA: ${idea}`,
  ].join('\n');
}

/**
 * Create a draft Work Order from an idea.
 * @param {{ idea: string, id?: string, level?: string, useAi?: boolean, force?: boolean, cwd?: string }} opts
 */
export async function planWorkOrder(opts) {
  const { root, paths, config } = loadConfig(opts.cwd);
  const idea = (opts.idea || '').trim();
  if (!idea) throw new Error('An idea is required: aiep plan "<your idea>"');

  const id = opts.id || nextWorkOrderId(paths.workOrders);
  if (!/^WO-\d{3,}$/.test(id)) throw new Error(`Invalid Work Order id "${id}" (expected WO-NNNN)`);

  const dir = join(paths.workOrders, id);
  const file = join(dir, 'work-order.md');
  if (existsSync(file) && !opts.force) {
    throw new Error(`${id} already exists. Use --id for a new id or --force to overwrite.`);
  }

  let fields = {};
  let usedAi = false;
  const wantAi = opts.useAi !== false;
  if (wantAi) {
    const spec = config.reviewers?.qwen || config.reviewers?.deepseek || {};
    const endpoint = spec.endpoint || 'http://127.0.0.1:11434';
    const probe = await probeOllama(endpoint);
    const model = probe.models.find((m) => m === spec.model || m.split(':')[0] === String(spec.model).split(':')[0]) || probe.models[0];
    if (probe.reachable && model) {
      try {
        const text = await ollamaGenerate(endpoint, model, buildPlanPrompt(idea), { numPredict: 400 });
        fields = parsePlanResponse(text);
        usedAi = true;
      } catch {
        usedAi = false; // fall back to template
      }
    }
  }

  // Defaults / validation.
  let level = opts.level || fields.level || 'L2';
  if (!VALID_LEVELS.includes(level)) level = 'L2';

  const md = renderWorkOrder({
    id,
    title: fields.title,
    level,
    rationale: fields.rationale,
    objective: fields.objective,
    deliverables: fields.deliverables,
    idea,
    usedAi,
  });

  mkdirSync(dir, { recursive: true });
  writeFileSync(file, md, 'utf8');

  return { id, path: file.replace(root + '\\', '').replace(root + '/', ''), level, usedAi };
}

function parseArgs(args) {
  const opts = { json: false, useAi: true, force: false };
  const ideaParts = [];
  for (let i = 0; i < args.length; i += 1) {
    const a = args[i];
    if (a === '--json') opts.json = true;
    else if (a === '--no-ai') opts.useAi = false;
    else if (a === '--force') opts.force = true;
    else if (a === '--id') opts.id = args[++i];
    else if (a.startsWith('--id=')) opts.id = a.slice(5);
    else if (a === '--level') opts.level = args[++i];
    else if (a.startsWith('--level=')) opts.level = a.slice(8);
    else if (!a.startsWith('-')) ideaParts.push(a);
  }
  opts.idea = ideaParts.join(' ');
  return opts;
}

export async function cmdPlan(args) {
  const opts = parseArgs(args);
  if (!opts.idea) {
    log.err('Usage: aiep plan "<your idea>" [--id WO-XXXX] [--level L1..L4] [--no-ai]');
    process.exitCode = 1;
    return;
  }
  if (!opts.json) log.step(`Drafting a Work Order from your idea${opts.useAi ? ' (asking the local model)…' : '…'}`);

  const result = await planWorkOrder(opts);

  if (opts.json) {
    log.info(JSON.stringify(result, null, 2));
    return;
  }
  log.header(`Draft Work Order created — ${result.id}`);
  log.info(`  File: ${c.cyan(result.path)}`);
  log.info(`  Suggested ReviewLevel: ${c.bold(result.level)}   Source: ${result.usedAi ? 'AI-assisted' : 'template (model unavailable)'}`);
  log.info(`  Status: ${c.yellow('backlog')} — draft for human review.`);
  log.header('Next steps');
  log.info(`  1. Review & refine ${result.path} (adjust scope, ReviewLevel, deliverables).`);
  log.info(`  2. Set status to planned / in-progress, implement the change.`);
  log.info(`  3. aiep review ${result.id} --last   # audit the change`);
  log.info(`  4. aiep validate`);
  log.warn('aiep plan only drafts a planning document — it does not write code or deploy.');
}
